version: '3.7'

services:
  haproxy:
    image: haproxy:2.3-alpine
    container_name: haproxy
    restart: unless-stopped
    command: [-f, /etc/haproxy/]
    network_mode: host
    volumes:
    - ./config.d/:/etc/haproxy/:ro
    - /etc/hosts:/etc/hosts:ro
