version: "3.7"
services:
  nexus:
    image: sonatype/nexus3:3.30.0
    container_name: nexus
    restart: unless-stopped
    network_mode: host
    volumes:
      - "/data/nexus:/nexus-data"
    ports:
      - "8081:8081" 
volumes:
  nexus-data: {}